//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudicijaKlijent.AudicijaServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Klijent", Namespace="http://schemas.datacontract.org/2004/07/DS4_Aukcija")]
    [System.SerializableAttribute()]
    public partial class Klijent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Eksponat", Namespace="http://schemas.datacontract.org/2004/07/DS4_Aukcija")]
    [System.SerializableAttribute()]
    public partial class Eksponat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KupacIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TrenutnaCenaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KupacId {
            get {
                return this.KupacIdField;
            }
            set {
                if ((this.KupacIdField.Equals(value) != true)) {
                    this.KupacIdField = value;
                    this.RaisePropertyChanged("KupacId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TrenutnaCena {
            get {
                return this.TrenutnaCenaField;
            }
            set {
                if ((this.TrenutnaCenaField.Equals(value) != true)) {
                    this.TrenutnaCenaField = value;
                    this.RaisePropertyChanged("TrenutnaCena");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AudicijaServis.IAudicijaServis")]
    public interface IAudicijaServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudicijaServis/PrijaviKlijenta", ReplyAction="http://tempuri.org/IAudicijaServis/PrijaviKlijentaResponse")]
        void PrijaviKlijenta(AudicijaKlijent.AudicijaServis.Klijent k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudicijaServis/PrijaviKlijenta", ReplyAction="http://tempuri.org/IAudicijaServis/PrijaviKlijentaResponse")]
        System.Threading.Tasks.Task PrijaviKlijentaAsync(AudicijaKlijent.AudicijaServis.Klijent k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudicijaServis/VratiEksponat", ReplyAction="http://tempuri.org/IAudicijaServis/VratiEksponatResponse")]
        AudicijaKlijent.AudicijaServis.Eksponat VratiEksponat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudicijaServis/VratiEksponat", ReplyAction="http://tempuri.org/IAudicijaServis/VratiEksponatResponse")]
        System.Threading.Tasks.Task<AudicijaKlijent.AudicijaServis.Eksponat> VratiEksponatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudicijaServis/Odustani", ReplyAction="http://tempuri.org/IAudicijaServis/OdustaniResponse")]
        bool Odustani(int k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudicijaServis/Odustani", ReplyAction="http://tempuri.org/IAudicijaServis/OdustaniResponse")]
        System.Threading.Tasks.Task<bool> OdustaniAsync(int k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudicijaServis/PovecajCenu", ReplyAction="http://tempuri.org/IAudicijaServis/PovecajCenuResponse")]
        int PovecajCenu(int k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudicijaServis/PovecajCenu", ReplyAction="http://tempuri.org/IAudicijaServis/PovecajCenuResponse")]
        System.Threading.Tasks.Task<int> PovecajCenuAsync(int k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudicijaServis/VratiKlijente", ReplyAction="http://tempuri.org/IAudicijaServis/VratiKlijenteResponse")]
        AudicijaKlijent.AudicijaServis.Klijent[] VratiKlijente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudicijaServis/VratiKlijente", ReplyAction="http://tempuri.org/IAudicijaServis/VratiKlijenteResponse")]
        System.Threading.Tasks.Task<AudicijaKlijent.AudicijaServis.Klijent[]> VratiKlijenteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAudicijaServisChannel : AudicijaKlijent.AudicijaServis.IAudicijaServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AudicijaServisClient : System.ServiceModel.ClientBase<AudicijaKlijent.AudicijaServis.IAudicijaServis>, AudicijaKlijent.AudicijaServis.IAudicijaServis {
        
        public AudicijaServisClient() {
        }
        
        public AudicijaServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AudicijaServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AudicijaServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AudicijaServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PrijaviKlijenta(AudicijaKlijent.AudicijaServis.Klijent k) {
            base.Channel.PrijaviKlijenta(k);
        }
        
        public System.Threading.Tasks.Task PrijaviKlijentaAsync(AudicijaKlijent.AudicijaServis.Klijent k) {
            return base.Channel.PrijaviKlijentaAsync(k);
        }
        
        public AudicijaKlijent.AudicijaServis.Eksponat VratiEksponat() {
            return base.Channel.VratiEksponat();
        }
        
        public System.Threading.Tasks.Task<AudicijaKlijent.AudicijaServis.Eksponat> VratiEksponatAsync() {
            return base.Channel.VratiEksponatAsync();
        }
        
        public bool Odustani(int k) {
            return base.Channel.Odustani(k);
        }
        
        public System.Threading.Tasks.Task<bool> OdustaniAsync(int k) {
            return base.Channel.OdustaniAsync(k);
        }
        
        public int PovecajCenu(int k) {
            return base.Channel.PovecajCenu(k);
        }
        
        public System.Threading.Tasks.Task<int> PovecajCenuAsync(int k) {
            return base.Channel.PovecajCenuAsync(k);
        }
        
        public AudicijaKlijent.AudicijaServis.Klijent[] VratiKlijente() {
            return base.Channel.VratiKlijente();
        }
        
        public System.Threading.Tasks.Task<AudicijaKlijent.AudicijaServis.Klijent[]> VratiKlijenteAsync() {
            return base.Channel.VratiKlijenteAsync();
        }
    }
}
